### ISSUE TITLE
can't find Subject.dict

### ISSUE THREAD

**Issue by Emily-zcy** [quyutest/node2defect#1]
Hello, I can't find Subject.dict. Do I need to generate it by myself ?

**Comment by quyutest** [comment]
@Emliy-zcy , thanks a lot for pointing out this. The previous repo is not a complete one. I have updated the repo now and added the file "Subject.dict". I have also updated the README.md file, please refer to the new file to reproduce the experiments. If you have any other questions, please feel free to let me know.

**Comment by Emily-zcy** [comment]
Thank you very much for your reply

**Comment by Emily-zcy** [comment]
I'm sorry to disturb you again. I still can't find the proNE.py to generate the embedding file.

**Comment by quyutest** [comment]
> I'm sorry to disturb you again. I still can't find the proNE.py to generate the embedding file.

@Emliy-zcy , you can download and configure ProNE's implementation at here: https://github.com/THUDM/ProNE, and then run the proNE.py.

**Comment by Emily-zcy** [comment]
Ok, thank you.
